enum SurpriseCost { free, low }

class PartnerSurprise {
  final int week;
  final String emoji;
  final String title;
  final String description;
  final String time;
  final String cost;
  final String bonus;

  const PartnerSurprise({
    required this.week,
    required this.emoji,
    required this.title,
    required this.description,
    required this.time,
    required this.cost,
    required this.bonus,
  });
}

const Map<int, PartnerSurprise> partnerSurprises = {
  1: PartnerSurprise(
    week: 1,
    emoji: '💌',
    title: 'The First Little Promise',
    description: 'Write one sentence about the kind of parent and partner you hope to be. Hide it somewhere your partner will find it later.',
    time: '5 min',
    cost: 'Free',
    bonus: 'Add a ridiculous signature like “CEO of Baby Operations.”',
  ),
  2: PartnerSurprise(
    week: 2,
    emoji: '🍓',
    title: 'Secret Snack Drop',
    description: 'Bring home one small snack your partner loves without being asked.',
    time: '10 min',
    cost: 'Low',
    bonus: 'Leave it with a note: “Saw this and thought of you.”',
  ),
  3: PartnerSurprise(
    week: 3,
    emoji: '🎵',
    title: 'Our Baby\'s First Playlist',
    description: 'Pick three songs together that you want your baby to hear someday.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Give the playlist a hilariously dramatic name.',
  ),
  4: PartnerSurprise(
    week: 4,
    emoji: '☕',
    title: 'No-Questions Tea Break',
    description: 'Make your partner their favorite drink and give them 15 completely interruption-free minutes.',
    time: '15 min',
    cost: 'Low',
    bonus: 'You handle every tiny chore during the break.',
  ),
  5: PartnerSurprise(
    week: 5,
    emoji: '😂',
    title: 'Baby Name Speed Round',
    description: 'Set a 3-minute timer and invent as many ridiculous baby names as possible.',
    time: '5 min',
    cost: 'Free',
    bonus: 'The winner gets to name an imaginary pet.',
  ),
  6: PartnerSurprise(
    week: 6,
    emoji: '📸',
    title: 'Tiny Time Capsule',
    description: 'Take one photo of yourselves exactly as you are this week.',
    time: '5 min',
    cost: 'Free',
    bonus: 'Write the date and one thing you were laughing about.',
  ),
  7: PartnerSurprise(
    week: 7,
    emoji: '🍕',
    title: 'Mystery Dinner',
    description: 'Choose your partner\'s dinner without telling them what it is until it arrives.',
    time: '30 min',
    cost: 'Low',
    bonus: 'Include one tiny surprise dessert.',
  ),
  8: PartnerSurprise(
    week: 8,
    emoji: '💃',
    title: 'Living-Room Dance Break',
    description: 'Put on one favorite song and dance together for its entire length.',
    time: '5 min',
    cost: 'Free',
    bonus: 'No choreography allowed.',
  ),
  9: PartnerSurprise(
    week: 9,
    emoji: '💌',
    title: 'Open-When Letter',
    description: 'Write a short letter for your partner to open on a stressful pregnancy day.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Seal it with a silly warning: “Open only when cuddles are medically required.”',
  ),
  10: PartnerSurprise(
    week: 10,
    emoji: '🎲',
    title: 'Would You Rather: Baby Edition',
    description: 'Take turns asking ridiculous baby-life “would you rather” questions.',
    time: '10 min',
    cost: 'Free',
    bonus: 'The stranger the question, the better.',
  ),
  11: PartnerSurprise(
    week: 11,
    emoji: '🧁',
    title: 'Tiny Celebration',
    description: 'Pick one little pregnancy milestone and celebrate it with a favorite treat.',
    time: '20 min',
    cost: 'Low',
    bonus: 'Give the milestone an official award title.',
  ),
  12: PartnerSurprise(
    week: 12,
    emoji: '🎤',
    title: 'Baby\'s First Interview',
    description: 'Pretend your future baby is giving an interview. Take turns answering as the baby.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Ask the baby their opinion on your cooking.',
  ),
  13: PartnerSurprise(
    week: 13,
    emoji: '🛋️',
    title: 'CEO of Comfort',
    description: 'For one evening, let your partner choose the snack, show, seating and schedule.',
    time: '30 min',
    cost: 'Low',
    bonus: 'Your only job is to make it happen.',
  ),
  14: PartnerSurprise(
    week: 14,
    emoji: '🧡',
    title: 'Three Things I Love',
    description: 'Tell your partner three things you appreciate about them that have nothing to do with pregnancy.',
    time: '5 min',
    cost: 'Free',
    bonus: 'One has to be something surprisingly specific.',
  ),
  15: PartnerSurprise(
    week: 15,
    emoji: '🍿',
    title: 'Mini Date at Home',
    description: 'Turn an ordinary evening into a tiny date with snacks, music and phones away.',
    time: '30 min',
    cost: 'Low',
    bonus: 'Give the evening a fake restaurant name.',
  ),
  16: PartnerSurprise(
    week: 16,
    emoji: '🗣️',
    title: 'Baby Pep Talk',
    description: 'Give the bump a completely ridiculous two-minute motivational speech.',
    time: '5 min',
    cost: 'Free',
    bonus: 'Use your most serious sports-commentator voice.',
  ),
  17: PartnerSurprise(
    week: 17,
    emoji: '🧩',
    title: 'Build a Baby Prediction',
    description: 'Each of you secretly predicts one funny personality trait your baby might have.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Save the predictions to compare after birth.',
  ),
  18: PartnerSurprise(
    week: 18,
    emoji: '🎨',
    title: 'Doodle the Family',
    description: 'Draw a silly picture of your future family together.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Stick it somewhere you\'ll both see it.',
  ),
  19: PartnerSurprise(
    week: 19,
    emoji: '🍫',
    title: 'Emergency Chocolate Mission',
    description: 'Surprise your partner with a favorite treat and declare it an official emergency.',
    time: '10 min',
    cost: 'Low',
    bonus: 'Create an unnecessarily serious emergency announcement.',
  ),
  20: PartnerSurprise(
    week: 20,
    emoji: '🎤',
    title: 'Talk to the Bump',
    description: 'Have a two-minute conversation with the baby as if they can answer back.',
    time: '5 min',
    cost: 'Free',
    bonus: 'Give the baby a temporary nickname.',
  ),
  21: PartnerSurprise(
    week: 21,
    emoji: '📷',
    title: 'The Candid Challenge',
    description: 'Take three completely unposed photos of your ordinary week together.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Pick the funniest one as the official week photo.',
  ),
  22: PartnerSurprise(
    week: 22,
    emoji: '🎶',
    title: 'One-Song Karaoke',
    description: 'Choose a song and perform it together at home.',
    time: '5 min',
    cost: 'Free',
    bonus: 'Bonus points for terrible dancing.',
  ),
  23: PartnerSurprise(
    week: 23,
    emoji: '🥞',
    title: 'Breakfast Surprise',
    description: 'Make or order your partner\'s favorite breakfast before they have to ask.',
    time: '20 min',
    cost: 'Low',
    bonus: 'Serve it with a handwritten “good morning” note.',
  ),
  24: PartnerSurprise(
    week: 24,
    emoji: '🧺',
    title: 'One Tiny Nest',
    description: 'Choose one small baby-related corner and make it nicer together.',
    time: '20 min',
    cost: 'Low',
    bonus: 'Stop after one corner — this is not a renovation project.',
  ),
  25: PartnerSurprise(
    week: 25,
    emoji: '💆',
    title: '15-Minute Relaxation Mission',
    description: 'Take over the little tasks while your partner gets 15 minutes to relax however they want.',
    time: '15 min',
    cost: 'Free',
    bonus: 'No asking what needs doing — look around and handle something.',
  ),
  26: PartnerSurprise(
    week: 26,
    emoji: '🎬',
    title: 'Our Trailer',
    description: 'Record a 30-second video trailer for the story of your growing family.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Use dramatic movie-trailer narration.',
  ),
  27: PartnerSurprise(
    week: 27,
    emoji: '🍦',
    title: 'Dessert Date',
    description: 'Go out for dessert or create a tiny dessert date at home.',
    time: '30 min',
    cost: 'Low',
    bonus: 'You both have to order something neither of you has tried.',
  ),
  28: PartnerSurprise(
    week: 28,
    emoji: '💭',
    title: 'Future Saturday',
    description: 'Imagine a completely ordinary Saturday with your child five years from now.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Each person describes one tiny detail.',
  ),
  29: PartnerSurprise(
    week: 29,
    emoji: '📝',
    title: 'Inside Joke Baby Book',
    description: 'Write down five silly phrases, jokes or memories from this pregnancy.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Give the collection a ridiculous title.',
  ),
  30: PartnerSurprise(
    week: 30,
    emoji: '🎁',
    title: 'Tiny Gift, Big Meaning',
    description: 'Give your partner one inexpensive little thing that says “I see you.”',
    time: '15 min',
    cost: 'Low',
    bonus: 'The gift can be as simple as their favorite snack.',
  ),
  31: PartnerSurprise(
    week: 31,
    emoji: '📱',
    title: 'Phone-Free Hour',
    description: 'Create one hour where both phones disappear and you just hang out.',
    time: '60 min',
    cost: 'Free',
    bonus: 'Prepare snacks first so nobody has an excuse to leave.',
  ),
  32: PartnerSurprise(
    week: 32,
    emoji: '🎵',
    title: 'Sing to the Baby',
    description: 'Choose one song and sing it together for the baby.',
    time: '5 min',
    cost: 'Free',
    bonus: 'It absolutely does not need to sound good.',
  ),
  33: PartnerSurprise(
    week: 33,
    emoji: '❤️',
    title: 'Memory Trade',
    description: 'Each person tells the other their favorite memory from your relationship so far.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Pick one memory you had forgotten about.',
  ),
  34: PartnerSurprise(
    week: 34,
    emoji: '🧸',
    title: 'Baby\'s Welcome Committee',
    description: 'Give the baby an absurdly formal welcome speech as if they\'re arriving at a very important conference.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Invent a job title for the baby.',
  ),
  35: PartnerSurprise(
    week: 35,
    emoji: '🍿',
    title: 'Comfort Movie Night',
    description: 'Let your partner choose the movie, food and seating. You handle everything else.',
    time: '120 min',
    cost: 'Low',
    bonus: 'No judging the movie choice.',
  ),
  36: PartnerSurprise(
    week: 36,
    emoji: '👜',
    title: 'Ready-for-Anything Basket',
    description: 'Put together a small basket of useful comfort items your partner may appreciate.',
    time: '20 min',
    cost: 'Low',
    bonus: 'Add one completely unnecessary but funny item.',
  ),
  37: PartnerSurprise(
    week: 37,
    emoji: '💌',
    title: 'The Gratitude Note',
    description: 'Write a note thanking your partner for one specific thing they\'ve done during pregnancy.',
    time: '10 min',
    cost: 'Free',
    bonus: 'Make it specific enough that they know you really noticed.',
  ),
  38: PartnerSurprise(
    week: 38,
    emoji: '🎲',
    title: 'Baby Trivia Battle',
    description: 'Take turns making up questions about your future baby and your life together.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Wrong answers earn bonus points if they\'re funny.',
  ),
  39: PartnerSurprise(
    week: 39,
    emoji: '🍽️',
    title: 'You Don\'t Plan Tonight',
    description: 'Take over dinner, chores and the evening plan completely.',
    time: '30 min',
    cost: 'Low',
    bonus: 'Your partner\'s only responsibility is choosing what sounds good.',
  ),
  40: PartnerSurprise(
    week: 40,
    emoji: '❤️',
    title: 'The Before-We-Meet Ritual',
    description: 'Sit together and each say three things you\'re excited to experience as a family.',
    time: '15 min',
    cost: 'Free',
    bonus: 'Finish by taking one photo together to remember the moment.',
  ),
};

PartnerSurprise? getPartnerSurprise(int week) => partnerSurprises[week];